### ISSUE TITLE
A question about dependencies

### ISSUE THREAD

**Issue by etoilestar** [A-Kerim/SyntheticData4VideoStabilization#1]
hello, I just emailed you yesterday, I can not install the dependencies neither by pypi nor conda, when I use conda, the command is 'conda create --name opflow --file conda_deps.txt', it tells me 'To search for alternate channels that may provide the conda package you're looking for, navigate to', and when I use pip, the command is 'pip install -r pip_deps.txt', it raise an error: 'Could not install packages due to an OSError: [Errno 2] No such file or directory: 'E:\\tmp\\build\\80754af9\\kiwisolver_1612282420641\\work'', could give me some guide? I run these command on win10 system, with rtx3080 graphic card, and the cuda version is 11.3. I am looking forward to your reply, thanks a lot.

**Comment by A-Kerim** [comment]
Hi, 

Are you sure you have "conda_deps.txt" in the correct directory? It seems this is an issue related to your conda setup. What is 'E:\tmp\build\80754af9\kiwisolver_1612282420641\work''?

Alternatively, you could just install the required packages yourself, and no need to use "conda_deps.txt". This file is just to facilitate the installation of all packages (with the required versions).
Thanks

**Comment by etoilestar** [comment]
Thank you so much for your reply，in fact，I tried to run train.py， flownet2 could not be found，so I copied this file from test package，but another error occurred，so I had a try to reinstall the dependence by pip and conda，but it did not work again.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 09/05/2022 18:18 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [A-Kerim/SyntheticData4VideoStabilization] A question about dependencies (Issue #1) |

Hi,

Are you sure you have "conda_deps.txt" in the correct directory? It seems this is an issue related to your conda setup. What is 'E:\tmp\build\80754af9\kiwisolver_1612282420641\work''?

Alternatively, you could just install the required packages yourself, and no need to use "conda_deps.txt". This file is just to facilitate the installation of all packages (with the required versions).
Thanks

**Comment by A-Kerim** [comment]
As stated in the "readme" file: 
**1.1 Please follow the instructions as described in https://github.com/NVIDIA/flownet2-pytorch to set up flownet2. Use the pre-trained model named "FlowNet2-S".**

**Comment by etoilestar** [comment]
thank you



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 09/05/2022 18:55 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [A-Kerim/SyntheticData4VideoStabilization] A question about dependencies (Issue #1) |

As stated in the "readme" file:
1.1 Please follow the instructions as described in https://github.com/NVIDIA/flownet2-pytorch to set up flownet2. Use the pre-trained model named "FlowNet2-S".

**Comment by etoilestar** [comment]
I just run train_tr.py， it raises a runtimee error，expected to have 4 channels，but got 2 channels instead.in honet


thank you



***@***.***
***@***.***



---- Replied Message ----
***@***.***>Date09/05/2022 ***@***.******@***.******@***.***>SubjectRe: [A-Kerim/SyntheticData4VideoStabilization] A question about dependencies (Issue #1)
As stated in the "readme" file:
1.1 Please follow the instructions as described in https://github.com/NVIDIA/flownet2-pytorch to set up flownet2. Use the pre-trained model named "FlowNet2-S".

**Comment by etoilestar** [comment]
and another question，line 136 in Data_Prep，the videos start from 35 to len，I am a little confused，because the length of part1 is 30.



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月06日 12:20 |
| 收件人 | ***@***.***> |
| 抄送至 | |
| 主题 | Re: [A-Kerim/SyntheticData4VideoStabilization] A question about dependencies (Issue #1) |
I just run train_tr.py， it raises a runtimee error，expected to have 4 channels，but got 2 channels instead.in honet


thank you



***@***.***
***@***.***



---- Replied Message ----
***@***.***>Date09/05/2022 ***@***.******@***.******@***.***>SubjectRe: [A-Kerim/SyntheticData4VideoStabilization] A question about dependencies (Issue #1)
As stated in the "readme" file:
1.1 Please follow the instructions as described in https://github.com/NVIDIA/flownet2-pytorch to set up flownet2. Use the pre-trained model named "FlowNet2-S".
